# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69d90ee74393ef9b8a3abc23bf30c12ce9a5be65d503e5150df7683e42fa81ebc5067e28f00e045cdc1fdc3062e230e0e9fbed00230cea8a3eb8b4dba2604138

test:
  secret_key_base: f4c7a81d88c602ae31df23d139e72c9c4aa05ebd75a5741b48108e69cff13920f008a58fba5fe7bb38641c6b17cd6415f22f01eb99310b03dee4993a7bace897

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
